name: Android CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Copy APK to builds folder
        run: |
          mkdir -p builds
          cp app/build/outputs/apk/debug/app-debug.apk builds/app-debug.apk

      - name: Commit and push APK
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add builds/app-debug.apk
          git commit -m "Add new APK build [skip ci]" || echo "No changes to commit"
          git push
